[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
acpi = { path = "../acpi" }
arch = { path = "../arch" }
uefi = { path = "../uefi" }
bootloader = { path = "../bootloader" }
boot_protocol_structures = { path = "../boot_protocol_structures" }