[build]
# rustflags = ["-C", "relocation-model=static", "-C", "code-model=kernel"]
rustflags = ["-C", "relocation-model=pic", "-C", "code-model=kernel"]

[unstable]
bindeps = true
#build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true