[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bootloader"
test = false
bench = false

[dependencies]
uefi = { path = "../uefi" }
kernel = { path = "../kernel" }
arch = { path = "../arch" }