[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bootloader"
test = false
bench = false

[dependencies]
uefi = { path = "../uefi" }
arch = { path = "../arch" }
acpi = { path = "../acpi" }
elf = { path = "../elf" }
boot_protocol_structures = { path = "../boot_protocol_structures" }